
---------------------------------------  SEED

-- Insertar en CLIENTE
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, DIRECCION) VALUES ('Juan', 'Pérez', 'juan.perez@example.com', '5551234567', 'Calle 1');
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, DIRECCION) VALUES ('Ana', 'García', 'ana.garcia@example.com', '5551234568', 'Calle 2');
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, DIRECCION) VALUES ('Luis', 'López', 'luis.lopez@example.com', '5551234569', 'Calle 3');
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, DIRECCION) VALUES ('María', 'Martínez', 'maria.martinez@example.com', '5551234570', 'Calle 4');
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, DIRECCION) VALUES ('Carlos', 'Sánchez', 'carlos.sanchez@example.com', '5551234571', 'Calle 5');
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, DIRECCION) VALUES ('Laura', 'Ramírez', 'laura.ramirez@example.com', '5551234572', 'Calle 6');
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, DIRECCION) VALUES ('Pedro', 'Torres', 'pedro.torres@example.com', '5551234573', 'Calle 7');
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, DIRECCION) VALUES ('Sofía', 'Flores', 'sofia.flores@example.com', '5551234574', 'Calle 8');
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, DIRECCION) VALUES ('Jorge', 'Castro', 'jorge.castro@example.com', '5551234575', 'Calle 9');
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, DIRECCION) VALUES ('Mónica', 'Hernández', 'monica.hernandez@example.com', '5551234576', 'Calle 10');

COMMIT;


-- Insertar en PRODUCTO
INSERT INTO PRODUCTO (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Laptop', 'Laptop HP 14"', 12000, 50);
INSERT INTO PRODUCTO (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Mouse', 'Mouse inalámbrico', 300, 200);
INSERT INTO PRODUCTO (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Teclado', 'Teclado mecánico', 800, 150);
INSERT INTO PRODUCTO (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Monitor', 'Monitor LED 24"', 3500, 75);
INSERT INTO PRODUCTO (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Impresora', 'Impresora multifuncional', 2500, 60);
INSERT INTO PRODUCTO (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Tablet', 'Tablet Samsung 10"', 8000, 40);
INSERT INTO PRODUCTO (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Auriculares', 'Audífonos Bluetooth', 1200, 90);
INSERT INTO PRODUCTO (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Smartphone', 'Teléfono Android', 10000, 30);
INSERT INTO PRODUCTO (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Silla Gamer', 'Silla ergonómica', 4500, 20);
INSERT INTO PRODUCTO (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES ('Webcam', 'Cámara web Full HD', 700, 100);

COMMIT;


-- Insertar en PEDIDO
INSERT INTO PEDIDO (ID_CLIENTE, TOTAL, ESTADO) VALUES ((SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'juan.perez@example.com'), 2500, 'PENDIENTE');
INSERT INTO PEDIDO (ID_CLIENTE, TOTAL, ESTADO) VALUES ((SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'ana.garcia@example.com'), 5000, 'ENVIADO');
INSERT INTO PEDIDO (ID_CLIENTE, TOTAL, ESTADO) VALUES ((SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'luis.lopez@example.com'), 1200, 'ENTREGADO');
INSERT INTO PEDIDO (ID_CLIENTE, TOTAL, ESTADO) VALUES ((SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'maria.martinez@example.com'), 800, 'PENDIENTE');
INSERT INTO PEDIDO (ID_CLIENTE, TOTAL, ESTADO) VALUES ((SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'carlos.sanchez@example.com'), 9800, 'CANCELADO');
INSERT INTO PEDIDO (ID_CLIENTE, TOTAL, ESTADO) VALUES ((SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'laura.ramirez@example.com'), 450, 'PENDIENTE');
INSERT INTO PEDIDO (ID_CLIENTE, TOTAL, ESTADO) VALUES ((SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'pedro.torres@example.com'), 7000, 'ENVIADO');
INSERT INTO PEDIDO (ID_CLIENTE, TOTAL, ESTADO) VALUES ((SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'sofia.flores@example.com'), 3200, 'ENTREGADO');
INSERT INTO PEDIDO (ID_CLIENTE, TOTAL, ESTADO) VALUES ((SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'jorge.castro@example.com'), 2100, 'PENDIENTE');
INSERT INTO PEDIDO (ID_CLIENTE, TOTAL, ESTADO) VALUES ((SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'monica.hernandez@example.com'), 6300, 'CANCELADO');

COMMIT;

-- Insertar en PEDIDO_PRODUCTO

INSERT INTO PEDIDO_PRODUCTO (ID_PEDIDO, ID_PRODUCTO, CANTIDAD)
VALUES (
  (SELECT ID_PEDIDO FROM PEDIDO WHERE ID_CLIENTE = (SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'juan.perez@example.com') AND TOTAL = 2500),
  (SELECT ID_PRODUCTO FROM PRODUCTO WHERE NOMBRE = 'Laptop'),
  1
);

INSERT INTO PEDIDO_PRODUCTO (ID_PEDIDO, ID_PRODUCTO, CANTIDAD)
VALUES (
  (SELECT ID_PEDIDO FROM PEDIDO WHERE ID_CLIENTE = (SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'juan.perez@example.com') AND TOTAL = 2500),
  (SELECT ID_PRODUCTO FROM PRODUCTO WHERE NOMBRE = 'Mouse'),
  2
);

INSERT INTO PEDIDO_PRODUCTO (ID_PEDIDO, ID_PRODUCTO, CANTIDAD)
VALUES (
  (SELECT ID_PEDIDO FROM PEDIDO WHERE ID_CLIENTE = (SELECT ID_CLIENTE FROM CLIENTE WHERE EMAIL = 'ana.garcia@example.com') AND TOTAL = 5000),
  (SELECT ID_PRODUCTO FROM PRODUCTO WHERE NOMBRE = 'Teclado'),
  1
);

COMMIT;