DROP SEQUENCE SEQ_CLIENTE;
-- Secuenicia para la tabla Cliente
CREATE SEQUENCE SEQ_CLIENTE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

DROP SEQUENCE SEQ_PRODUCTO;
-- Secuencia para la tabla PRODUCTO
CREATE SEQUENCE SEQ_PRODUCTO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;



DROP SEQUENCE SEQ_PEDIDO;
-- Secuencia para la tabla PEDIDO
CREATE SEQUENCE SEQ_PEDIDO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;



DROP TABLE CLIENTE CASCADE CONSTRAINTS;
-- Tabla CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER DEFAULT CLIENTE_SEQ.NEXTVAL,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    TELEFONO VARCHAR2(10) NOT NULL UNIQUE,
    DIRECCION VARCHAR2(100),
    FECHA_ELIMINACION DATE DEFAULT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT CK_TELEFONO CHECK (REGEXP_LIKE(TELEFONO, '^\d{10}$')),
    CONSTRAINT CK_EMAIL CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'))
);

DROP TABLE PRODUCTO CASCADE CONSTRAINTS;
-- Tabla PRODUCTO
CREATE TABLE PRODUCTO (
    ID_PRODUCTO NUMBER DEFAULT PRODUCTO_SEQ.NEXTVAL,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(255) NOT NULL,
    PRECIO NUMBER(10,2) NOT NULL CHECK (PRECIO >= 0),
    STOCK NUMBER NOT NULL CHECK (STOCK >= 0),
    CONSTRAINT PRODUCTO_PK PRIMARY KEY (ID_PRODUCTO)
);

DROP TABLE PEDIDO CASCADE CONSTRAINTS;
-- Tabla PEDIDO
CREATE TABLE PEDIDO (
    ID_PEDIDO NUMBER DEFAULT PEDIDO_SEQ.NEXTVAL,
    ID_CLIENTE NUMBER NOT NULL,
    TOTAL NUMBER(10,2) NOT NULL CHECK (TOTAL >= 0),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    ESTADO VARCHAR2(20) DEFAULT 'PENDIENTE',
    CONSTRAINT PEDIDO_PK PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

DROP TABLE PEDIDO_PRODUCTO CASCADE CONSTRAINTS;
-- Tabla PEDIDO_PRODUCTO (relación N:N)
CREATE TABLE PEDIDO_PRODUCTO  (
    ID_PEDIDO NUMBER NOT NULL,
    ID_PRODUCTO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL CHECK (CANTIDAD > 0),
    PRIMARY KEY (ID_PEDIDO, ID_PRODUCTO),
    CONSTRAINT FK_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT FK_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);