-- Secuencia para la tabla CLIENTE
CREATE SEQUENCE SEQ_CLIENTE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para la tabla PRODUCTO
CREATE SEQUENCE SEQ_PRODUCTO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para la tabla PEDIDO
CREATE SEQUENCE SEQ_PEDIDO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


ALTER TABLE CLIENTE
MODIFY ID_CLIENTE DEFAULT SEQ_CLIENTE.NEXTVAL;

ALTER TABLE PRODUCTO
MODIFY ID_PRODUCTO DEFAULT SEQ_PRODUCTO.NEXTVAL;

ALTER TABLE PEDIDO
MODIFY ID_PEDIDO DEFAULT SEQ_PEDIDO.NEXTVAL;

-- Tabla CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    TELEFONO VARCHAR2(10) NOT NULL UNIQUE,
    DIRECCION VARCHAR2(100),
    FECHA_ELIMINACION DATE DEFAULT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT CK_TELEFONO CHECK (REGEXP_LIKE(TELEFONO, '^\d{10}$')),
    CONSTRAINT CK_EMAIL CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'))
);

-- Tabla PRODUCTO
CREATE TABLE PRODUCTO (
    ID_PRODUCTO NUMBER,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(255) NOT NULL,
    PRECIO NUMBER(10,2) NOT NULL CHECK (PRECIO >= 0),
    STOCK NUMBER NOT NULL CHECK (STOCK >= 0),
    CONSTRAINT PRODUCTO_PK PRIMARY KEY (ID_PRODUCTO)
);

-- Tabla PEDIDO
CREATE TABLE PEDIDO (
    ID_PEDIDO NUMBER,
    ID_CLIENTE NUMBER NOT NULL,
    TOTAL NUMBER(10,2) NOT NULL CHECK (TOTAL >= 0),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    ESTADO VARCHAR2(20) DEFAULT 'PENDIENTE',
    CONSTRAINT PEDIDO_PK PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- Tabla PEDIDO_PRODUCTO (relación N:N)
CREATE TABLE PEDIDO_PRODUCTO (
    ID_PEDIDO NUMBER NOT NULL,
    ID_PRODUCTO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL CHECK (CANTIDAD > 0),
    PRIMARY KEY (ID_PEDIDO, ID_PRODUCTO),
    CONSTRAINT FK_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT FK_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);


-- Trigger para CLIENTE
CREATE OR REPLACE TRIGGER TRG_CLIENTE_BI
BEFORE INSERT ON CLIENTE
FOR EACH ROW
BEGIN
    IF :NEW.ID_CLIENTE IS NULL THEN
        SELECT SEQ_CLIENTE.NEXTVAL INTO :NEW.ID_CLIENTE FROM DUAL;
    END IF;
END;


-- Trigger para PRODUCTO
CREATE OR REPLACE TRIGGER TRG_PRODUCTO_BI
BEFORE INSERT ON PRODUCTO
FOR EACH ROW
BEGIN
    IF :NEW.ID_PRODUCTO IS NULL THEN
        SELECT SEQ_PRODUCTO.NEXTVAL INTO :NEW.ID_PRODUCTO FROM DUAL;
    END IF;
END;
/

-- Trigger para PEDIDO
CREATE OR REPLACE TRIGGER TRG_PEDIDO_BI
BEFORE INSERT ON PEDIDO
FOR EACH ROW
BEGIN
    IF :NEW.ID_PEDIDO IS NULL THEN
        SELECT SEQ_PEDIDO.NEXTVAL INTO :NEW.ID_PEDIDO FROM DUAL;
    END IF;
END;
/
